# Generated by Django 4.2.2 on 2023-08-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_category_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_nmae',
            new_name='category_name',
        ),
    ]
